### ISSUE TITLE
코드 통일성

### ISSUE THREAD

**Issue by gwiseki** [18-1-SKKU-OSS/2018-1-OSS-L9#2]
2018-1-OSS-L9/timezones/tzlib_win_x64/makefile
에 보시면 ' = '  전후로 전부 띄어쓰기가 안되어있는데 위에서부터 ' = '가 들어가는 두 줄만 띄어쓰기가 되어있네요.

띄어쓰기 없이 수정하면 어떨까요?

**Comment by rubybee** [comment]
그렇게 하죠

**Comment by Manshimaro** [comment]
좋은 생각입니다.

**Comment by gwiseki** [comment]
네 그럼 수정하도록 하겠습니다.
